### PR TITLE
use autoconf escape hatch to default to MADV_FREE

### PR DESCRIPTION
**Pull request by srosenberg**
(see https://github.com/cockroachdb/cockroach/issues/83790)

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
My knowledge of autoconf is super out of date, but this seems strange to me. I thought `config.cache` was a cache, as its name implies. I would expect that there is a better way for specifying a config setting than stuffing it in the cache. Also, does this even have the right effect since we compile jemalloc using cmake? The answer might very well be yes, but let's document the autoconf black magic going on here both in a comment and in the commit message. In addition to documenting how this is working, please document why we want to set `MADV_FREE`.

**Comment by srosenberg** [comment]
> My knowledge of autoconf is super out of date, but this seems strange to me. I thought `config.cache` was a cache, as its name implies.

Same here. It's only after I came across the following, mentioned in [1],

> In some cases it may be necessary to work around configuration results that do not match reality. For example, Linux 4.5 added support for the MADV_FREE flag to madvise(2), which can cause problems if building on a host with MADV_FREE support and deploying to a target without. To work around this, use a cache file to override the relevant configuration variable defined in configure.ac, e.g.:

```
echo "je_cv_madv_free=no" > config.cache && ./configure -C
```

> I would expect that there is a better way for specifying a config setting than stuffing it in the cache.

Maybe. E.g., we could patch the configure script to unconditionally disable `madv_free`, but that seems more intrusive.

> Also, does this even have the right effect since we compile jemalloc using cmake? 

It does; the [linked PR](https://github.com/cockroachdb/cockroach/pull/83795/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R624) ensures that the configured makefile has disabled `madv_free`.

> In addition to documenting how this is working, please document why we want to set `MADV_FREE`.

This is documented in the [linked issue](https://github.com/cockroachdb/cockroach/issues/83790).

[1] https://android.googlesource.com/platform/external/jemalloc_new/+/refs/heads/master/INSTALL.md

**Comment by rickystewart** [comment]
I agree the `config.cache` thing is weird here. I would expect you can just set this value as an environment variable. For example when building `libkrb5` we set `ac_cv_func_regcomp=yes` as an environment variable. Did you try that and confirm it does not work?

**Comment by nicktrav** [comment]
Is this something we could pass in at build time (i.e. in Cockroach, via Bazel)?

In ideal world, our fork would only contain patches that are ultimately upstreamable, but are yet to be released. Adding a Cockroach-specific patch that would be unlikely to be accepted upstream seems counter to that.

edit: Ricky beat me to the punchline :)

**Comment by srosenberg** [comment]
> I agree the `config.cache` thing is weird here. I would expect you can just set this value as an environment variable. For example when building `libkrb5` we set `ac_cv_func_regcomp=yes` as an environment variable. Did you try that and confirm it does not work?

Setting the env. var seems to work. Thanks for suggestion! I'll update make and bazel scripts in the corresponding PR; closing this one.

**Pull request closed without merging**
